vm_name = "testing"
vm_size = "Standard_DS1_v2"
vnet_name = "testing"
subnet_name = "testing"
location = "East US"
vnet_address_space = ["10.0.0.0/16"]
subnet_address_prefixes = ["10.0.2.0/24"]
nic_name = "testing"
resource_group_name = "testing"
